SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [VENDAS_SUCOS].[DBO].[PRODUTOS] WHERE [CODIGO] = '1000889'

UPDATE [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 7
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT 
	B.[CODIGO DO PRODUTO], 
	B.[PREÇO DE LISTA], 
	A.[CODIGO], 
	A.[PREÇO LISTA]

FROM [VENDAS_SUCOS].[DBO].[PRODUTOS] AS A 
INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] AS B ON A.[CODIGO] = B.[CODIGO DO PRODUTO]
WHERE A.[CODIGO] = '1000889'

UPDATE A SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA]
FROM [VENDAS_SUCOS].[DBO].[PRODUTOS] AS A 
INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] AS B ON A.[CODIGO] = B.[CODIGO DO PRODUTO]
WHERE A.[CODIGO] = '1000889'

SELECT 
	 A.CPF
	,A.[VOLUME DE COMPRA]
FROM [VENDAS_SUCOS].[DBO].[CLIENTES] AS A
INNER JOIN [VENDAS_SUCOS].[DBO].[VENDEDORES] AS B ON A.[BAIRRO] = B.[BAIRRO]

UPDATE A SET A.[VOLUME DE COMPRA] = A.[VOLUME DE COMPRA] * 1.30
FROM [VENDAS_SUCOS].[DBO].[CLIENTES] AS A 
INNER JOIN [VENDAS_SUCOS].[DBO].[VENDEDORES] AS B ON A.[BAIRRO] = B.[BAIRRO]
