SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002334'

SELECT * FROM [VENDAS_SUCOS].[DBO].[PRODUTOS] WHERE [CODIGO] = '1002334'

SELECT 
	B.[CODIGO DO PRODUTO], 
	B.[PREÇO DE LISTA], 
	A.[CODIGO], 
	A.[PREÇO LISTA]

FROM [VENDAS_SUCOS].[DBO].[PRODUTOS] AS A 
INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] AS B ON A.[CODIGO] = B.[CODIGO DO PRODUTO]
WHERE [CODIGO] = '1002334'

UPDATE [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 8
WHERE [CODIGO DO PRODUTO] = '1002334'

MERGE INTO [VENDAS_SUCOS].[DBO].[PRODUTOS] AS A
USING [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] AS B ON A.[CODIGO] = B.[CODIGO DO PRODUTO]
AND A.[CODIGO] = '1002334'
WHEN MATCHED THEN
UPDATE SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA];

MERGE INTO [VENDAS_SUCOS].[DBO].[CLIENTES] A
USING [VENDAS_SUCOS].[DBO].[VENDEDORES] B
ON A.[BAIRRO] = B.[BAIRRO]
WHEN MATCHED THEN
UPDATE SET A.[VOLUME DE COMPRA] = 
    A.[VOLUME DE COMPRA] * 1.30;