--CREATE DATABASE VENDAS_SUCOS;

--USE VENDAS_SUCOS;

CREATE TABLE [PRODUTOS] (
	 [CODIGO] VARCHAR (10) NOT NULL
	,[DESCRITOR] VARCHAR (100) NULL
	,[SABOR] VARCHAR (50) NULL
	,[TAMANHO] VARCHAR (50) NULL
	,[EMBALAGEM] VARCHAR (50) NULL
	,[PREÇO LISTA] FLOAT NULL
	,CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CODIGO])
)
GO

CREATE TABLE [VENDEDORES] (
	 [MATRICULA] VARCHAR (5) NOT NULL
	,[NOME] VARCHAR (100) NULL
	,[BAIRRO] VARCHAR (50) NULL
	,[COMISSAO] FLOAT NULL
	,[DATA DE ADMISSAO] DATE NULL
	,[FERIAS] BIT NULL
	,CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([MATRICULA])
)
GO

CREATE TABLE [dbo].[CLIENTES](
    [CPF] VARCHAR(11) NOT NULL,
    [NOME] VARCHAR(50) NULL,
    [ENDEREÇO] VARCHAR(100) NULL,
    [BAIRRO] VARCHAR(50) NULL,
    [CIDADE] VARCHAR(50) NULL,
    [ESTADO] VARCHAR(50) NULL,
    [CEP] VARCHAR(8) NULL,
    [DATA NASCIMENTO] DATE NULL,
    [IDADE] INT NULL,
    [SEXO] VARCHAR(1),
    [LIMITE DE CRÉDITO] FLOAT,
    [VOLUME DE COMPRA] FLOAT,
    [PRIMEIRA COMPRA] BIT, 
    CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED ([CPF])
)
GO;

USE [VENDAS SUCOS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITENS VENDIDOS](
    [NÚMERO] VARCHAR(5) NOT NULL,
    [CÓDIGO] VARCHAR(10) NOT NULL,
    [QUANTIDADE] INT NULL,
    [PREÇO] FLOAT NULL, 
CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED (
    [NÚMERO] ASC, [CÓDIGO] ASC
) WITH (
    PAD_INDEX = OFF, 
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = OFF, 
    ALLOW_ROW_LOCKS = ON, 
    ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTES]
FOREIGN KEY ([CPF]) REFERENCES [CLIENTES] ([CPF])

