SELECT * FROM [CLIENTES]
WHERE [CPF] = '19290992743'

SELECT * FROM [CLIENTES]
WHERE [ESTADO] = 'RJ'

UPDATE [CLIENTES] SET [ENDEREÇO] = 'R. Jorge Emilio 23', [BAIRRO] = 'Santo Amaro', [CIDADE] = 'São Paulo', [ESTADO] = 'SP', [CEP] = 8833223
	WHERE [CPF] = '19290992743'

UPDATE [dbo].[CLIENTES] SET [VOLUME DE COMPRA] = [VOLUME DE COMPRA] * 1.2 
	WHERE [ESTADO] = 'RJ'

