DECLARE @QtdNotas INT
DECLARE @DataNota DATE

SET @DataNota = '2017-01-10'
SET @QtdNotas = (SELECT COUNT (*) FROM [SUCOS_VENDAS].[dbo].[NOTAS FISCAIS] WHERE [DATA] = @DataNota)

PRINT @QtdNota

IF @QtdNotas >= 70
    PRINT 'Muita Nota'
ELSE
    PRINT 'Pouca Nota'

----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x----x

USE SUCOS_VENDAS

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT

SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'

WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE [DATA] = @DATAINICIAL
    PRINT CONVERT(VARCHAR(10), @DATAINICIAL) + ' --> ' 
        + CONVERT(VARCHAR(10), @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END