
	 SELECT * FROM [VENDAS_SUCOS].[DBO].[PRODUTOS] 
	 WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 DELETE FROM [VENDAS_SUCOS].[DBO].[PRODUTOS]  
	 WHERE [CODIGO] = '1001000'

	 SELECT * FROM [VENDAS_SUCOS].[DBO].[PRODUTOS]   
	 WHERE [TAMANHO] = '1 Litro' AND SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 DELETE FROM [VENDAS_SUCOS].[DBO].[PRODUTOS]  
	 WHERE [TAMANHO] = '1 Litro' AND SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 SELECT [CODIGO DO PRODUTO] 
	 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]

	 SELECT * FROM [VENDAS_SUCOS].[DBO].[PRODUTOS]  
	 WHERE [CODIGO] NOT IN (SELECT [CODIGO DO PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS])

	 DELETE FROM [VENDAS_SUCOS].[DBO].[PRODUTOS]  
	 WHERE [CODIGO] NOT IN (SELECT [CODIGO DO PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS])

	 SELECT 
		A.NÚMERO 
	 FROM [VENDAS_SUCOS].[DBO].[NOTAS] AS A
	 INNER JOIN [VENDAS_SUCOS].[DBO].[CLIENTES] AS B ON A.[CPF] = B.[CPF] 
	 WHERE B.[IDADE] < 18

	DELETE A FROM [VENDAS_SUCOS].[DBO].[NOTAS] AS A
	INNER JOIN [VENDAS_SUCOS].[DBO].[CLIENTES] AS B ON A.[CPF] = B.[CPF] 
	WHERE B.[IDADE] < 18