USE VENDAS_SUCOS

SELECT * FROM [VENDEDORES]

BEGIN TRANSACTION

UPDATE [VENDEDORES] SET [COMISSAO] = [COMISSAO] * 1.15

INSERT INTO [VENDEDORES] ([MATRICULA], [NOME], [BAIRRO],[COMISSAO],[DATA DE ADMISSAO], [FERIAS])
VALUES ('99999','João da Silva','Icarai',0.08,'2014-09-01',0)

ROLLBACK

COMMIT